<VBS>
  <SEQUENCE>
    <DESCRIPTION>BLU</DESCRIPTION>
    <FILE>C:\SDLCCANFLASH\BLU_FOR_SDLC\LU5T-14F532-BAA.VBF</FILE>
    <FILE>C:\SDLCCANFLASH\BLU_FOR_SDLC\BLU-BLK1.vbf</FILE>
    <FILE>C:\SDLCCANFLASH\BLU_FOR_SDLC\BLU-BLK2.vbf</FILE>
    <KEY_FILE />
    <ECD_FILE />
  </SEQUENCE>
</VBS>